package org.example.design.generator.base.set;

public enum Watercolors {
    ZINC,LEMON_YELLO,MEDIUM_YELLOW,DEEP_YELLOW,ORANGE,
    BRILLIANT_RED,CRIMSON,MAGENTA,ROSE_MADDER,VIOLET,
    CERULEAN_BLUE_HUE,PHTHALO_BLUE,ULTRAMARINE,VIRIDINA_HUE
}
